### PR TITLE
Update daily.js

### PR DESCRIPTION
**Pull request by ReportCardsMC**
Add a random amount of points from 25 - 200

### CODE REVIEW

**Comment by ckiee** [comment]
i don't really think this would be a good idea

**Comment by jellz** [comment]
ehh I don't really like that idea, if someone would like to express their opinions about this feel free to re-open this PR

**Denied.**

**Comment by ThatTonybo** [comment]
My view on this would be good. Instead of giving people 100 points every time, you'd have a diversity and a kind of "luck game", which would certainly spice up the experience with the new command. 

And yeah, I literally commented right after it was closed. *shrugs*

**Comment by jellz** [comment]
@RileyDatLord @ThatTonybo If you can get some :+1: reactions I'll consider it. React to the main message.

**Comment by jellz** [comment]
**Denied.**

**Pull request closed without merging**
